name: データ取得ワークフロー
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 4-16 * * 3'
    - cron: '0 */6 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: main
          clean: true
      - name: データのダウンロード
        run: |
          pip install -r ./collect-db/requirements.txt
          python ./collect-db/src/
      - name: ブランチの整理
        run: |
          find . -mindepth 1 \( -path './dist' -o -path './.git' \) -prune -o -exec rm -rf {} +
          mv dist/* .
          rm -rf dist
          git add .
      - name: 差分チェック
        run: |
          if git ls-remote --heads origin pages | grep -q "refs/heads/pages"; then
            git fetch origin pages
            if ! git diff --cached --quiet origin/pages -- ':(exclude)module/data/metadata.json'; then
              echo "FLOW_STOP=0" >> $GITHUB_ENV
            else
              echo "FLOW_STOP=1" >> $GITHUB_ENV
            fi
          else
            echo "FLOW_STOP=0" >> $GITHUB_ENV
          fi
      - name: 変更をコミット
        if: ${{ env.FLOW_STOP == '0' }}
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git checkout --orphan temp
          git add -A
          git commit -m "最新のデータを更新"
          git checkout pages
          git reset --hard temp
          git branch -D temp
          git push -f origin pages
